config/routes.rb
Hdmovies::Application.routes.draw do
  get "home/index"

  get "home/chat"

  resources :requests do
    member do
      post 'fill'
    end
  end

  resources :users do
    member do
      post 'add_to_list'
      post 'remove_from_list'
      get 'remove_from_list'
      get  'critics'
      get  'mustsee'
    end
  end
  
  resources :user_sessions
  
  resources :critics do
    collection do
      get :rss
    end
  end

  resources :movies do
    collection do
      get :rss
      get :autocomplete_movie_title
    end
    member do
      get :freebase
    end
  end
  
  resources :genres
  
  # some non restful routes for movies
  match 'movies_grid'   => 'movies#grid'
  match 'movies_sgrid'  => 'movies#sgrid'
  match 'movies_full'   => 'movies#full'
  match 'stats'         => 'movies#stats'
  match 'year(/:id)'    => 'movies#year' , :as => :year
  
  # config/routes.rb
  #map.login "login", :controller => "user_sessions", :action => "new"
  #map.logout "logout", :controller => "user_sessions", :action => "destroy"

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "home#index" #controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :require_user, :except => [:index]
  before_filter(:only => :index) do |controller|
    controller.send(:require_user) unless (controller.request.format.rss? || controller.request.format.json?)
  end
  
  autocomplete :movie, :title #, :extra_data => [:alt_title]
  
  respond_to :html
  
  # GET /movies
  # GET /movies.xml
  def index
    if params[:s]
      @movies = Movie.where("title LIKE '\%#{params[:s]}\%'").order('created_at DESC').paginate :per_page => 20, :page => params[:page]
      @movies = Movie.where("alt_title LIKE '\%#{params[:s]}\%'").order('created_at DESC').paginate :per_page => 20, :page => params[:page] unless @movies.size>0
      @movies = Movie.where("\"cast\" LIKE '\%#{params[:s]}\%'").order('created_at DESC').paginate :per_page => 20, :page => params[:page] unless @movies.size>0
      @movies = Movie.where("\"director\" LIKE '\%#{params[:s]}\%'").order('created_at DESC').paginate :per_page => 20, :page => params[:page] unless @movies.size>0
    elsif params[:m]
      @movies = Movie.where("tvserie != ''").order('created_at DESC').paginate :per_page => 20, :page => params[:page]
    else
      if params[:order]
        case params[:order]
        when 'score'
          order = "imdb_score DESC"
        when 'title'
          order = "title ASC"
        when 'year'
          order = "year DESC"
        when 'average'
          order = "average_score DESC"
        end
      else
        order = "created_at DESC"
      end
      if params[:genre]
        @movies = Movie.tagged_with(params[:genre]).order(order).paginate(:per_page => 20, :page => params[:page]) unless @movies
      else
        @movies = Movie.order(order).paginate(:per_page => 20, :page => params[:page]) unless @movies
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      #format.iphone # index.iphone.erb
      format.rss { render :layout => false } #index.rss.builder
      format.json { render_for_api :base, :json => @movies }
      format.xml { render_for_api :base, :xml => @movies, :root => :movies }
    end
  end
  
  def grid
    @movies = Movie.where("photo_file_name IS NOT NULL").order('created_at DESC').paginate :per_page => 16, :page => params[:page]
  end
  
  def sgrid
    @movies = Movie.where("photo_file_name IS NOT NULL").order('created_at DESC').paginate :per_page => 40, :page => params[:page]
  end

  def full
    @movies = Movie.order('title ASC')
  end
  
  def year
    if params[:id]
      @movies = Movie.where(["year = ?", params[:id].to_i]).order('year DESC,created_at DESC')
    else
      @movies = Movie.where("year IS NOT NULL").order('year DESC,created_at DESC')
    end
  end
  
  # GET /movies/1
  # GET /movies/1.xml
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.iphone #{ render :layout => false } # show.iphone.erb
      format.xml  { render :xml => @movie }
      format.json { render_for_api :base, :json => @movie }
      format.xml { render_for_api :base, :xml => @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.xml
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end
  
  # try to get data from freebase and redirect to edit with some fields filled
  # save still needs to be done
  # GET /movies/1/freebase?freebase_slug=
  def freebase
    require 'net/http'
    begin
      @movie = Movie.find(params[:id])
      
      # if we get a slug, we update the row
      if params[:freebase_slug]
        @movie.update_attribute('freebase', params[:freebase_slug])
      end
      
      # TODO : put that in model
      url = 'http://www.freebase.com/experimental/topic/standard' + @movie.freebase
      resp = Net::HTTP.get_response( URI.parse(url) )
      json = JSON.parse(resp.body)
      @result = json['result']
      raise unless @result

      # see example of json to parse : http://www.freebase.com/experimental/topic/standard/m/09k56b7
      @movie.alt_title = @result['text']
      @movie.country = @result['properties']['/film/film/country']['values'][0]['text']
      @movie.body = @result['description']
      @movie.genre_list = @result['properties']['/film/film/genre']['values'].map{|g| g['text']} #.join(',')
      @movie.year = @result['properties']['/film/film/initial_release_date']['values'][0]['value'].split('-')[0]
      @movie.director = @result['properties']['/film/film/directed_by']['values'].map{|g| g['text']}.join(', ')
      @movie.cast = @result['properties']['/film/film/starring']['values'].map{|g| g['text'].split('-')[0].rstrip}.join(', ')
      
      @result['webpage'].each{|p|
        @movie.url_imdb = p['url'] if p['text'] == 'IMDB Title Page'
        @movie.apple_url = p['url'] if p['url'] =~ /trailers\.apple\.com/i
        @movie.youtube_url = p['url'] if p['text'] =~ /youtube/i
        @movie.wikipedia_url = p['url'] if p['text'] == 'Wikipedia'
      }

      if params[:save]=='true'
        @movie.save
        redirect_to(@movie, :notice => 'Data updated with ' + url)
        return
      end
      
=begin
      if @movie.freebase
        # its way better to have the code
        slug = '/m/' + @movie.freebase.split('/').last
      else
        slug = '/en/' + @movie.title.rstrip.gsub(/\s/,'_').downcase
      end
      @resource = Ken.get(slug)
      raise if @resource.nil?
      @movie.director = @resource.attribute('/film/film/directed_by') unless @movie.director
      @movie.year = @resource.attribute('/film/film/initial_release_date').to_s.split('-').first
      @movie.country = @resource.attribute('/film/film/country').to_s.split(/\n/).first
      @movie.plot = @resource.attribute('/film/film/tagline')
      
      puts @resource.attribute('/film/film/initial_release_date').to_s.split('-').first
      puts @resource.attribute('/film/film/country')
      puts @resource.attribute('/film/film/tagline')
      #render 'edit'
=end
    #rescue
    #  redirect_to(@movie, :notice => 'No data found on Freebase, you could change freebase code : ' + @movie.freebase)
    end  
  end

  # POST /movies
  # POST /movies.xml
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to(@movie, :notice => 'Movie was successfully created.') }
        format.xml  { render :xml => @movie, :status => :created, :location => @movie }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.xml
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to(@movie, :notice => 'Movie was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.xml
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to(movies_url) }
      format.xml  { head :ok }
    end
  end
  
  # some basic stats
  def stats
    @movies_size = Movie.count
    @movies_w_pics_size = Movie.count(:conditions => "photo_file_name IS NOT NULL")
    @critics_size = Critic.count
    @users_size = User.count
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_assets_links.html.erb
<a target="_blank" href="http://www.google.com/images?q=<%= @movie.title.gsub('\s','+') -%>+%3F&um=1&hl=fr&tbs=isch:1,isz:m">Google Image</a>
<a target="_blank" href="http://www.bing.com/images/search?q=<%= @movie.title.gsub('\s','+') -%>&go=&form=QBLH&scope=images&filt=all">Bing Image</a>
<a target="_blank" href="http://www.imdb.com/find?s=all&q=<%= @movie.title.gsub('\s','+') -%>">Imdb</a>
<a target="_blank" href="http://www.youtube.com/results?search_query=<%= @movie.title.gsub('\s','+') -%>">Youtube</a>
<a target="_blank" href="https://www.freebase.com/search?limit=30&start=0&query=<%= @movie.title.gsub('\s','+') -%>">Freebase</a>

app/views/movies/_form.html.erb
<%= form_for(@movie, :html => { :multipart => true }) do |f| %>
<% if @movie.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this request from being saved:</h2>

    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<div style="float:right">

	<div class="actions">
	  <%= f.submit %> <%= link_to 'Cancel', @movie %>
	</div>

  <div class="field">
    <%= f.label :genres %><br />
    <%= f.text_area :genre_list, :rows => 2 %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :plot %><br />
    <%= f.text_area :plot, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>

  <div class="field">
    <%= f.label :cast %><br />
    <%= f.text_area :cast, :rows => 3 %>
  </div>
<hr>

  <div>
    <%= f.label(:photo, 'Upload photo') %>
    <%= f.file_field(:photo) %>
  </div>
  <%- unless @movie.new_record? || !@movie.photo? -%>
    <div>
  		<%= f.label(:delete_photo, 'Delete photo') %>
  		<%= f.check_box(:delete_photo) %>
	<br>
      <%= image_tag(@movie.photo.url(:large), :alt => 'Photo', :title => 'Current photo') %>
    
    </div>
  <%- end -%>

<hr>

</div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title , :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :alt_title %><br />
    <%= f.text_field :alt_title , :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.select :year, (1910..Time.now.year+1).to_a.reverse, :include_blank => TRUE %>
  </div>

  <div class="field">
    <%= f.label :episodes %><br />
    <%= f.text_field :episodes , :size => 15 %> <%= f.check_box(:tvserie) %> is a <%= f.label :tvserie %>
  </div>

  <div class="field">
    <%= f.label :origin %><br />
    <%= f.select :origin, ['','hdfrench','tehconnection','allotracker','gks','sharetheremote','bt','other'] %>
  </div>

  <div class="field">
    <%= f.label :url_imdb %><br />
    <%= f.text_field :url_imdb , :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :imdb_score %><br />
    <%= f.text_field :imdb_score %>
  </div>
  <div class="field">
    <%= f.label :quality %><br />
    <%= f.select :quality, ['','720p','1080p','480p','other'] %>
  </div>
  <div class="field">
    <%= f.label :format %><br />
    <%= f.select :format, ['','mkv','avi','mov','mp4','other'] %>
  </div>

  <div class="field">
    <%= f.label :languages %><br />
    <%= f.text_field :languages %>
  </div>
  <div class="field">
    <%= f.label :subs %><br />
    <%= f.text_field :subs %>
  </div>

  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename , :size => 40 %> <%= f.check_box(:deleted) %> <%= f.label :deleted %><br>
  </div>

  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %> Gb
  </div>
  <div class="field">
    <%= f.label :freebase %><br />
    <%= f.text_field :freebase %>
  </div>

  <div class="field">
    <%= f.label :youtube_url %><br />
    <%= f.text_field :youtube_url %>
  </div>
  <div class="field">
    <%= f.label :embed_movie %><br />
    <%= f.text_area :embed_movie, :rows => 2 %>
  </div>
  <div class="field">
    <%= f.label :apple_url %><br />
    <%= f.text_field :apple_url %>
  </div>
  <div class="field">
    <%= f.label :amazon_url %><br />
    <%= f.text_field :amazon_url %>
  </div>
  <div class="field">
    <%= f.label :url_allocine %><br />
    <%= f.text_field :url_allocine %>
  </div>
  <div class="field">
    <%= f.label :wikipedia_url %><br />
    <%= f.text_field :wikipedia_url %>
  </div>
  <div class="field">
    <%= f.label :traileraddict_url %><br />
    <%= f.text_field :traileraddict_url %>
  </div>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:user_id, User.all, :id, :username) %>
  </div>


  <div class="actions">
    <%= f.submit %> <%= link_to 'Cancel', @movie %>
  </div>
<% end %>

app/views/movies/_movie_tr.html.erb
  <tr>
	<td>
	<% if movie.photo_file_name %>
	<%= image_tag(movie.photo.url(:small), :alt => movie.title) %> 
	<% else %>
	add
	<% end %>
	</td>
	<td valign="top">
	<b class="large"><%= movie.year -%></b>
	</td>

    <td valign="top">
	<span class="movie_title">
		<%= link_to movie.title, movie_path(movie), :style => (movie.deleted ? 'text-decoration: line-through' : '') %>
	</span>
	<% if movie.alt_title && movie.alt_title.size>0 %><br><%= movie.alt_title -%><% end %>
	<% if movie.director && movie.director.size>0 %><br><span class="small"><strong>by</strong> <%= movie.director %></span><% end %>
	<% if movie.cast && movie.cast.size>0%><br><span class="small"><strong>with</strong> <%= movie.cast %></span><% end %>
	<p>	<% if movie.genre_list && movie.genre_list.size>0 %><br><span class="small_genre"><%= movie.genre_list -%></span><% end %>
	</p>
	</td>
	<td valign="top" width="90">
		<% if movie.critics.size>0 %>
		<div class="big_score score"><%= number_with_precision(movie.average, :precision => 1) -%></div>
		<br><%= movie.critics.size %> critic<br>
			<% if current_user.critic_on(movie) %>
				<%= image_tag "checked.png" -%>
			<% end %>
		<% else %>
		<%= link_to 'add first critic', movie_path(movie), :class => "button inline" -%>
		<% end %>
		</td>
    <td valign="top">
		<table border="0" cellpadding="0">
			<tr>
				<td>Quality:</td>
				<td><%= movie.quality %></td>
			</tr>
			<tr>
				<td>Format:</td>
				<td><%= movie.format -%></td>
			</tr>
			<tr>
				<td>Audio:</td>
				<td><%= movie.languages %></td>
			</tr>
			<tr>
				<td>Subs:</td>
				<td><%= movie.subs %></td>
			</tr>
		</table>
	</td>
	
	<td width="80" align="center" valign="top">
	<% if movie.imdb_score %>
		<div class="big_score">
		<%= link_to movie.imdb_score, movie.url_imdb, :target => '_blank' %>
		</div> 
	<% end %>
	</td>
    
<!--     <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, :confirm => 'Are you sure?', :method => :delete %></td>
 -->  </tr>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

app/views/movies/freebase.html.erb
<%= link_to 'back to film', movie_path -%> | <%= link_to 'save this data', freebase_movie_path(:save => true) -%> 

<hr>
<h1><%= @movie.title -%></h1>
<h2>Ready for saving this data</h2>
Alt Title : <%= @movie.alt_title -%>
<hr>
Genres : <%= @movie.genre_list -%>
<hr>
Cast : <%= @movie.cast -%>
<hr>
IMDB URL : <%= @movie.url_imdb -%>
<hr>

Apple URL : <%= @movie.apple_url -%>
<hr>
Youtube URL : <%= @movie.youtube_url -%>
<hr>
Wikipedia URL : <%= @movie.wikipedia_url -%>


<h2>More data</h2>
<%= @result.keys -%>
<hr>
<%= @movie.inspect -%>
<hr>

app/views/movies/freebase_ken.html.erb
<%= @resource.attribute('/film/film/tagline') -%>

<%= @movie.inspect -%>

<hr>
<% for t in @resource.types %>
<%= t.inspect -%> : <%= t -%><br>
<% end %>

<hr>
<% for t in @resource.attributes %>
<%= t.inspect -%> : <%= t -%><br>
	<% t.values.each{|m| %>
		&nbsp;&nbsp;&nbsp;&nbsp;<%= m.inspect -%> : <%= m -%><br>
	<% } %>
<% end %>

<hr>
<% for t in @resource.views %>
<%= t.inspect -%> : <%= t -%><br>
<% end %>

app/views/movies/full.html.erb
<table border="1" cellspacing="1" cellpadding="2">
	<tr><th>Name</th>
	<th>Imdb</th>
	<th>Genres</th>
	<th>Qual.</th>
	<th>Lang</th>
	<th>Subs</th>
	</tr>
	<% for movie in @movies %>
	<tr>
		<td><strong><%= link_to movie.title, movie_path(movie), :style => (movie.deleted ? 'text-decoration: line-through' : '') %></strong></td>
		<td>
			<strong>
			<% if movie.url_imdb && movie.imdb_score %>
			<%= link_to movie.imdb_score, movie.url_imdb %>
			<% else %>
			<%= movie.imdb_score -%>
			<% end %></strong> 
		</td>
		<td><%= movie.genre_list -%></td>
		<td><%= movie.quality %></td>
	    <td><%= movie.languages %></td>
	    <td><%= movie.subs %></td>
	    
	</tr>
	<% end %>
</table>

app/views/movies/grid.html.erb
<% @movies.each do |movie| %>
	<% if movie.photo_file_name %>
	<a href="/movies/<%= movie.id -%>"><%= image_tag(movie.photo.url(:medium), :alt => movie.title) %> </a>
	<% end %>
<% end %>

<%= will_paginate @movies %> 

app/views/movies/index.html.erb
<table width="100%" border="1" cellspacing="0" cellpadding="3" style="border-collapse:collapse;border:1px solid lightgrey">
  <tr>
	<th></th>
    <th><a href="/movies?order=year">Year</a></th>
    <th><a href="/movies?order=title">Title</a></th>
    <th><a href="/movies?order=average">Aver.</a></th>
    <th>Spec.</th>
    <th><a href="/movies?order=score">Imdb</a></th>
  </tr>

<% @movies.each do |movie| %>
<%= render :partial => 'movie_tr', :locals => {:movie => movie} -%>
<% end %>
</table>

<%= will_paginate @movies %> 

<a href="/movies_full">full list</a>

app/views/movies/index.iphone.erb
<div data-role="header"><h1>Last movies</h1></div> 

<div data-role="content">
  <ul data-role="listview">
    <% @movies.each do |movie| %>
    <li>
   	<% if movie.photo_file_name %>
	<%= image_tag(movie.photo.url(:xsmall), :alt => movie.title) %> 
	<% end %>

      <%= link_to movie.title, movie %>
      <%# link_to 'edit movie', edit_movie_path(movie), "data-icon" => "gear" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/sgrid.html.erb
<% @movies.each do |movie| %>
	<% if movie.photo_file_name %>
	<a href="/movies/<%= movie.id -%>"><%= image_tag(movie.photo.url(:small), :alt => movie.title) %> </a>
	<% end %>
<% end %>

<%= will_paginate @movies %>

app/views/movies/show.html.erb
<div class="grid_11">
	<h1 class="movie_title large_movie_title"><%= @movie.tvserie ? 'Serie : ' : '' -%><%= @movie.title %> <% if @movie.year %>(<%= @movie.year %>)<% end %></h1>
</div>
<div class="grid_1" style="padding-top:14px">
	<% if @movie.imdb_score %>
		<div class="big_score">
		<%= link_to @movie.imdb_score, @movie.url_imdb %>
		</div> 
	<% end %>
</div>

<div class="clear"></div> 
<div class="grid_12">
	<div id="movie_menu" class="menu" style="float:left">
	<% if current_user.superuser %>
	<%= link_to 'Edit movie', edit_movie_path(@movie) %> 
	<%= link_to 'Destroy movie', @movie, :confirm => "Are you sure?", :method => :delete %>
	<%= link_to 'Freebase lookup', freebase_movie_path(@movie) %>
	<% end %>
	<% if current_user.movies.include?(@movie) %>
	<%= link_to 'Remove from wishlist', remove_from_list_user_path(current_user, {:movie => @movie}) , :method => :post %>
	<% else %>
	<%= link_to 'Add to my wishlist', add_to_list_user_path(current_user, {:movie => @movie}) , :method => :post %>
	<% end %>
	<%= render :partial => "assets_links" -%>
	</div>
</div>

<div class="clear"></div>

<div class="grid_6"> 
	<p> 
		<%- unless !@movie.photo? -%>
		<%= image_tag(@movie.photo.url(:large), :alt => 'Photo', :title => 'Current photo') %><br>
		<%- end -%>

<table border="1" cellspacing="0" cellpadding="2" class="xsmall border-collapse" width="90%">
	<tr>
		<td><b>Quality:</b></td>
		<td><%= @movie.quality %></td>
		
		<td><b>Filename:</b></td>
		<td><% @movie.filename %> <% if @movie.deleted %>DELETED<% end %></td>
		
	</tr>
	<tr>
		<td><b>Languages:</b></td>
		<td><%= @movie.languages %></td>
		
		<td><b>Added by:</b></td>
		<td><%= link_to @movie.user.username, @movie.user %></td>
	</tr>
	
	<tr>
		<td><b>Subs:</b></td>
		<td><%= @movie.subs %></td>

		<td><b>In the wishlist of:</b></td>
		<td><% for u in  @movie.users %><%= link_to u.username, user_path(u) -%> <% end %> </td>
	</tr>
	
	<tr>
		<td><b>Format:</b></td>
		<td><%= @movie.format %></td>

		<% if @movie.freebase %>
		<td><b>Freebase:</b></td>
		<td><%= link_to @movie.freebase, "http://www.freebase.com/view" + @movie.freebase %></td>
		<% else %>
		<td></td>
		<td></td>
		<% end %>
	</tr>
	
	<tr>
		<td><b>Origin</b></td>
		<td><%= @movie.origin %></td>
		
		<td></td>
		<td></td>
	</tr>
	
</table>

<br>
<br>
<% if current_user.superuser %>
<form action="<%= url_for freebase_movie_path -%>" method="GET">
Try freebase : <input type="text" name="freebase_slug" /><input type="submit" name="submit" value="Try" id="submit">
</form>
<% end %>

	</p> 
</div> 
<!-- end .grid_4 --> 
<div class="grid_6"> 
	<p> 
		<p>
			<em><%= @movie.alt_title %></em>
		</p>
<% if @movie.tvserie %>
		<p>
			<strong>Episodes</strong> : <%= @movie.episodes -%>
		</p>
<% end %>
		<p>
			<% if @movie.url_imdb && @movie.url_imdb.size>1 %>
			<b>Imdb url:</b>
			<%= link_to @movie.url_imdb,@movie.url_imdb %><br>
			<% end %>
			<% if @movie.youtube_url && @movie.youtube_url.size>1 %>
			<b>Youtube url:</b>
			<%= link_to @movie.youtube_url,@movie.youtube_url %><br>
			<% end %>
			<% if @movie.apple_url && @movie.apple_url.size>1 %>
			<b>Apple url:</b>
			<%= link_to @movie.apple_url,@movie.apple_url %><br>
			<% end %>
			<% if @movie.wikipedia_url && @movie.wikipedia_url.size>1 %>
			<b>Wikipedia:</b>
			<%= link_to @movie.wikipedia_url,@movie.wikipedia_url %><br>
			<% end %>
			<% if @movie.traileraddict_url && @movie.traileraddict_url.size>1 %>
			<b>TrailerAddict:</b>
			<%= link_to @movie.traileraddict_url,@movie.traileraddict_url %>
			<% end %>
		</p>
		
		<p>
			<strong>Genres</strong> : <%= @movie.genre_list -%>
		</p>

		<p>
			<b>Director:</b>
			<%= @movie.director %>
		</p>


		<p>
			<b>Cast:</b>
			<%= @movie.cast %>
		</p>

		<p>
			<b>Country:</b>
			<%= @movie.country %>
		</p>

		<p>
			<b>Body:</b>
			<%= snippet(@movie.body) %>
		</p>

		<p>
			<b>Plot:</b>
			<%= markdown(@movie.plot) %>
		</p>

<!--		<p>
			<b>Amazon url:</b>
			<%= @movie.amazon_url %>
		</p>

<p>
	<b>Embed movie:</b>
	<%= @movie.embed_movie %>
</p>


		<p>
			<b>Url allocine:</b>
			<%= @movie.url_allocine %>
		</p> -->

	</p> 



	<H3><%= @movie.critics.size -%> Critics (average score : <%= number_with_precision(@movie.average_score, :precision => 2) -%> / 20)</h3>

		<% if current_user && !current_user.critic_on(@movie) %>
		<% @critic = Critic.new(:movie_id => @movie.id) %>
		<%= render :partial => '/critics/form' -%>
		<% end %>

		<% for c in @movie.critics %>
		by <strong><%= link_to c.user.username, c.user -%></strong> <% if c.score %><strong>(<%= c.score -%>/20)</strong><% end %>
		<% if c.user==current_user %><%= link_to "edit this critic", edit_critic_path(c) -%><% end %>
		<br>
		<%= markdown(c.content) -%>
		<hr />
		<% end %>

	<!-- <div id="fb-root"></div><script src="http://connect.facebook.net/fr_FR/all.js#appId=189039117779667&amp;xfbml=1"></script>
	<fb:comments xid="hdiesta_movie_<%= @movie.id -%>" numposts="8" width="460" publish_feed="false"></fb:comments> -->


</div>

<div class="clear"></div> 

app/views/movies/stats.html.erb
<h2>Stats</h2>
Movies : <%= @movies_size -%><br>
Movies with pic: <%= @movies_w_pics_size -%><br>
Critics : <%= @critics_size -%><br>
Users : <%= @users_size -%>