config/routes.rb
Hdmovies::Application.routes.draw do
  get "home/index"

  get "home/chat"

  resources :requests do
    member do
      post 'fill'
    end
  end

  resources :users do
    member do
      post 'add_to_list'
      post 'remove_from_list'
      get 'remove_from_list'
      get  'critics'
      get  'mustsee'
    end
  end
  
  resources :user_sessions
  
  resources :critics do
    collection do
      get :rss
    end
  end

  resources :movies do
    collection do
      get :rss
      get :autocomplete_movie_title
    end
    member do
      get :freebase
    end
  end
  
  resources :genres
  
  # some non restful routes for movies
  match 'movies_grid'   => 'movies#grid'
  match 'movies_sgrid'  => 'movies#sgrid'
  match 'movies_full'   => 'movies#full'
  match 'stats'         => 'movies#stats'
  match 'year(/:id)'    => 'movies#year' , :as => :year
  
  # config/routes.rb
  #map.login "login", :controller => "user_sessions", :action => "new"
  #map.logout "logout", :controller => "user_sessions", :action => "destroy"

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "home#index" #controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  acts_as_api
  
  has_many :critics
  
  api_accessible :base do |template|
     template.add :id
     template.add :username
     template.add :critics_count
  end
  
  has_many :critics, :order => "created_at DESC"
  has_many :requests
  has_and_belongs_to_many :movies, :join_table => "users_movies", :order => "users_movies.created_at DESC"
  
  def critic_on(movie)
    return Critic.find(:first, :conditions => ["movie_id = ? AND user_id = ?", movie.id, self.id])
  end
  
#  def as_json(options={})
#    logger.debug "as_json called"
#    super(:except => [:created_at, :updated_at, :crypted_password, :current_login_at, :current_login_ip, :email, :failed_login_count, :last_login_ip, :last_request_at, ])
#  end

  # used by api
  def critics_count
    self.critics.count
  end
  
  # this return a list of movie not yet criticized
  def mustsee
    # must use this 2 steps becausesqlite doe snot support right joins or the join i needed
    seen = Critic.where(["user_id = ?",self.id]).select('movie_id').map{|m| m.movie_id}.join(',')
    Movie.where("id NOT IN (#{seen})")
  end
  
  # average score
  def average_score
    self.critics.average('score')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :only => [:index, :show, :edit, :update, :destroy]
  # GET /users
  # GET /users.xml

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
  
  # GET /users/1/critics
  def critics
    @user = User.find(params[:id])
    @critics = @user.critics.paginate(:per_page => 15, :page => params[:page])
    respond_to do |format|
      format.html # critics.html.erb
    end
  end
  
  # GET /users/1/mustsee
  def mustsee
    @user = User.find(params[:id])
    @movies = @user.mustsee.order('created_at DESC').paginate(:per_page => 25, :page => params[:page])
    respond_to do |format|
      format.html # critics.html.erb
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(root_url, :notice => 'Registration succesfull.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  # POST /users/1/add_to_list (?movie=9)
  def add_to_list
    @user = User.find(params[:id])
    @movie = Movie.find(params[:movie])
    @user.movies << @movie
    respond_to do |format|
      format.html { redirect_to(@movie, :notice => 'Movie was added to your wishlist.') }
      format.xml  { render :xml => @user }
    end
  end

  # POST /users/1/add_to_list (?movie=9)
  def remove_from_list
    @user = User.find(params[:id])
    @movie = Movie.find(params[:movie])
    @user.movies.delete(@movie)
    respond_to do |format|
      format.html { redirect_to(@movie, :notice => 'Movie was removed from your wishlist.') }
      format.xml  { render :xml => @user }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/critics.html.erb
<h1>Critics of <%= link_to @user.username, user_path(@user) -%></h1>
<%= will_paginate @critics -%>
<% for critic in @critics %>
<div class="grid_6" style="padding-bottom:20px">
<%= render :partial => '/critics/critic_tr', :locals => {:critic => critic} -%>
</div>
<% end %>
<div class="clear"></div> 
<%= will_paginate @critics -%>

app/views/users/edit.html.erb
<h1>Modify profile</h1>

<%= render 'form' %>

<%= link_to 'See profile', @user %>

app/views/users/index.html.erb
<h1>HD users</h1>

<table width="100%">
  <tr align="left">
    <th>Username</th>
    <th>Email</th>
	<th>Critics</th>
	<th>Average score</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.username, user %> <% if user.superuser %><% end %></td>
    <td><%= user.email %></td>
	<td><%= user.critics.size -%></td>
	<td><%= number_to_human user.average_score -%></td>
  </tr>
<% end %>
</table>

<br />
<% if current_user.superuser %>
<%= link_to 'New user', new_user_path %>
<% end %>

app/views/users/mustsee.html.erb
<h2>Mustsee of <%= @user.username -%> <span class="small">not yet criticized</span></h2>
<table width="100%" border="1" cellspacing="0" cellpadding="3" style="border-collapse:collapse;border:1px solid lightgrey">
<% for movie in @movies %>
<%= render :partial => '/movies/movie_tr', :locals => {:movie => movie} -%>
<% end %>
</table>
<%= will_paginate @movies -%>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>
  <b>Username:</b>
  <%= @user.username %> (<%= @user.email %>)
</2>

<h2>Wants to see</h2>
<% for movie in @user.movies %>
<% if movie.photo_file_name %>
<a href="/movies/<%= movie.id -%>"><%= image_tag(movie.photo.url(:small), :alt => movie.title, :class => 'autopic') %> </a>
<% end %>
<% end %>


<h2>Last critics <a href="<%= critics_user_path(@user) -%>" class="small">see all</a></h2>

<% i=0 %>
<% for critic in @user.critics.order('created_at DESC').limit(20) %>
	<div class="grid_6" style="padding-bottom:20px">
	<%= render :partial => '/critics/critic_tr', :locals => {:critic => critic} -%>
	</div>
<% end %>
<div class="clear"></div> 

<% if current_user.superuser %>
<br>
<hr><br>
<%= link_to 'Edit user', edit_user_path(@user) %> |
<%= link_to 'All users', users_path %>
<% end %> 