config/routes.rb
Hdmovies::Application.routes.draw do
  get "home/index"

  get "home/chat"

  resources :requests do
    member do
      post 'fill'
    end
  end

  resources :users do
    member do
      post 'add_to_list'
      post 'remove_from_list'
      get 'remove_from_list'
      get  'critics'
      get  'mustsee'
    end
  end
  
  resources :user_sessions
  
  resources :critics do
    collection do
      get :rss
    end
  end

  resources :movies do
    collection do
      get :rss
      get :autocomplete_movie_title
    end
    member do
      get :freebase
    end
  end
  
  resources :genres
  
  # some non restful routes for movies
  match 'movies_grid'   => 'movies#grid'
  match 'movies_sgrid'  => 'movies#sgrid'
  match 'movies_full'   => 'movies#full'
  match 'stats'         => 'movies#stats'
  match 'year(/:id)'    => 'movies#year' , :as => :year
  
  # config/routes.rb
  #map.login "login", :controller => "user_sessions", :action => "new"
  #map.logout "logout", :controller => "user_sessions", :action => "destroy"

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "home#index" #controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name
  validates_presence_of :url
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :require_user

  protect_from_forgery :except => [:fill]

  # GET /requests
  # GET /requests.xml
  def index
    @requests = Request.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.xml
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.xml
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.xml
  def create
    @request = Request.new(params[:request])
    @request.user_id = current_user.id
    respond_to do |format|
      if @request.save
        format.html { redirect_to(requests_url, :notice => 'Request was successfully created.') }
        format.xml  { render :xml => @request, :status => :created, :location => @request }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.xml
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to(@request, :notice => 'Request was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def fill
    @request = Request.find(params[:id])
    movie = Movie.find(params[:fill_id].to_i)
    notice = "Data missing"

    if movie
      @request.filled_id = movie.id
      @request.save
      notice = "Request filled"
    end
    redirect_to(requests_url, :notice => notice)
    
    rescue
      redirect_to(requests_url, :notice => notice)
  end

  # DELETE /requests/1
  # DELETE /requests/1.xml
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to(requests_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Requests</h1>
<%= link_to 'Add a Request', new_request_path %> for movies you are looking for...
<br><br>
<table cellpadding="3" border="1" width="100%">

<% @requests.each do |request| %>
  <tr>
	<td style="font-size:22px"><a href="<%= request.url -%>"><%= request.name %></a></td>
	<td>asked by <a href="/users/<%= request.user.id -%>"><%= request.user.username %></a></td>
<!--      <td><%= link_to 'Show', request %></td>
    <td><%= link_to 'Edit', edit_request_path(request) %></td>
 -->
<td>
<% if request.filled_id %> 
<span style="color:green"><a href="/movies/<%= request.filled_id -%>">Filled </a></span>
<% end %>
</td>

<td>
<% if current_user==request.user %>
<%= link_to 'delete', request, :confirm => 'Are you sure?', :method => :delete %></form>
<% end %>
</td>

<td>
<% if current_user.superuser %>
<% unless request.filled_id %>
<form action="/requests/<%= request.id -%>/fill" method="post"><input type="text" name="fill_id" size="5" /> 
<input type="submit" value="fill" />
</form>
<% end %>
<% end %>
</td>

</tr>
<% end %>
</table>

<br />

app/views/requests/new.html.erb
<h1>Add request</h1>

<%= render 'form' %>

<%= link_to 'All requests', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>