config/routes.rb
Hdmovies::Application.routes.draw do
  get "home/index"

  get "home/chat"

  resources :requests do
    member do
      post 'fill'
    end
  end

  resources :users do
    member do
      post 'add_to_list'
      post 'remove_from_list'
      get 'remove_from_list'
      get  'critics'
      get  'mustsee'
    end
  end
  
  resources :user_sessions
  
  resources :critics do
    collection do
      get :rss
    end
  end

  resources :movies do
    collection do
      get :rss
      get :autocomplete_movie_title
    end
    member do
      get :freebase
    end
  end
  
  resources :genres
  
  # some non restful routes for movies
  match 'movies_grid'   => 'movies#grid'
  match 'movies_sgrid'  => 'movies#sgrid'
  match 'movies_full'   => 'movies#full'
  match 'stats'         => 'movies#stats'
  match 'year(/:id)'    => 'movies#year' , :as => :year
  
  # config/routes.rb
  #map.login "login", :controller => "user_sessions", :action => "new"
  #map.logout "logout", :controller => "user_sessions", :action => "destroy"

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "home#index" #controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_rightmenu.html.erb
<div id="menu" class="menu" style="float:right">
	<% if current_user %>
	<%= link_to "account: " + current_user.username , user_path(current_user.id) %> 
	<%= link_to "mustsee", mustsee_user_path(current_user) %>
	<% if current_user.superuser %>
	<a href="/movies/new" id="new">add movie</a> 
	<a href="/users" id="new">users list</a> 
	<% end %>
	<%= link_to "logout", logout_path %>
	<% else %>
	<!-- <%= link_to "Register", new_user_path %> -->
	<%= link_to "Login", login_path %>
	<% end %>
</div><br/>
<div id="menu2" class="menu" style="float:right;padding-top:9px">
	<a href="/movies" id="list">Movies</a> 
	<a href="/movies_grid" id="new">L</a> <a href="/movies_sgrid" id="new">S</a> 
	<!-- <a href="/movies/?m=series" id="list">Series</a> -->
	<a href="/requests" id="list">Requests</a>
	<a href="/genres" id="new">Tags</a> 
	<a href="/year" id="new">Years</a> 
	<a href="/critics" id="list">Critics</a>
	<a href="/stats" id="list">Stats</a>
</div>
</div>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html>
<head>
<title><% if @movie %><%= @movie.title -%><% else %>HDMovies<% end %></title>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister&v2"> 
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tag %>
</head>
<body>
<div id="container">
	<div class="container_12">
		<div class="grid_3"> 
			<div id="logo"><a href="/"><%= image_tag 'logo.png' -%></a></div>
		</div>
		<div class="grid_2">
			<form action="/movies" method="GET"><input name="s" type="search" id="s" size="18" placeholder="Search"  data-autocomplete="movies/autocomplete_movie_title"></form>
			<div id="menu3" class="" style="">
				&nbsp;
				<a href="https://twitter.com/<%= TwitterAccount -%>" title="Twitter" target="_blank"><%= image_tag "twitter.png" -%></a>
				<a href="/movies.rss" id="rss" target="_blank"  title="Movies RSS"><%= image_tag "rss.png" -%></a> 
				<a href="/critics.rss" id="rss" target="_blank" title="Critics RSS"><%= image_tag "crss.png" -%></a> 
			</div>
		</div>
		<div class="grid_7">
		<%= render :partial => '/layouts/rightmenu' -%>
		<div class="clear"></div> 
		<div class="grid_12">
			<% if notice %>
			<p class="notice"><%= notice %></p>
			<% end %>
		</div>
		<div class="container_12">
			<hr>
		</div>
	<%= yield %>
	<div class="container_12">
		<hr>
		<p>
			iesta/sucrenoir : <a href="http://twitter.com/sucrenoir">Twitter</a> | <a href="http://ordiman.tumblr.com">Tumblr</a> | <a href="https://github.com/iesta">On Github</a>
		</p>
		
	</div>
</div>
</body>
</html>

app/views/layouts/layout.iphone.erb
<html>
<head>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.css" />
	<script src="http://code.jquery.com/jquery-1.6.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.js"></script>
	<script>
 function BlockMove(event) {
  // Tell Safari not to move the window.
  event.preventDefault() ;
 }
</script>
	<title>HDMovies Mobile</title>
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="default" />
	<meta name="viewport" content="user-scalable=no, width=device-width" />
</head>
<body ontouchmove="BlockMove(event);">
<div data-role="page">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/movies.html.erb
<!DOCTYPE html>
<html>
<head>
<title><% if @movie %><%= @movie.title -%><% else %>HDMovies<% end %></title>
<%= stylesheet_link_tag 'movies','960' %>
<%= javascript_include_tag :defaults, 'jrumble' %>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<%= csrf_meta_tag %>
</head>
<body>
<div id="container">
	<div class="container_12">
		<div class="grid_3"> 
			<div id="logo"><a href="/"><img src="/images/logo.png" alt="HDMovies" /></a></div>
		</div>
		<div class="grid_2">
			<form action="/movies" method="GET"><input name="s" type="search" id="s" size="18" placeholder="Search"></form>
			<div id="menu3" class="" style="">
				&nbsp;
				<a href="https://twitter.com/<%= TwitterAccount -%>" title="Twitter" target="_blank"><%= image_tag "twitter.png" -%></a>
				<a href="/movies.rss" id="rss" target="_blank"  title="Movies RSS"><%= image_tag "rss.png" -%></a> 
				<a href="/critics.rss" id="rss" target="_blank" title="Critics RSS"><%= image_tag "crss.png" -%></a> 
			</div>
		</div>
		<div class="grid_7">
		<%= render :partial => '/layouts/rightmenu' -%>
		<div class="clear"></div> 
		<div class="grid_12">
			<% if notice %>
			<p class="notice"><%= notice %></p>
			<% end %>
		</div>
		<div class="container_12">
			<hr>
		</div>
	<%= yield %>
	<div class="container_12">
		<hr>
		<p>
			iesta/sucrenoir : <a href="http://twitter.com/sucrenoir">Twitter</a> | <a href="http://ordiman.tumblr.com">Tumblr</a> | <a href="https://github.com/iesta">On Github</a>
		</p>
		
	</div>
</div>
</body>
</html>

app/views/layouts/movies.iphone.erb
<html>
<head>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.css" />
	<script src="http://code.jquery.com/jquery-1.5.2.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.js"></script>
	<script>
 function BlockMove(event) {
  // Tell Safari not to move the window.
  event.preventDefault() ;
 }
</script>
	<title>HDMovies Mobile</title>
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="default" />
	<meta name="viewport" content="user-scalable=no, width=device-width" />
</head>
<body ontouchmove="BlockMove(event);">
<div data-role="page">
<%= yield %>
</div>
</body>
</html>